import { useState, useEffect, useCallback, useRef } from 'react';
import { useAuth } from '../context/AuthContext';
import { leaderAPI } from '../services/api';
import { getQueuedSubmissionForDate } from '../services/offlineDB';
import useOffline from './useOffline';
import { formatLocalDate } from '../utils/date';

const WEEKDAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

const normalizeDay = (day) => (day || '').trim().toLowerCase();

const getWeekdayNameForDate = (dateString) => {
  const parsed = dateString ? new Date(`${dateString}T12:00:00`) : new Date();
  if (Number.isNaN(parsed.getTime())) {
    return WEEKDAY_NAMES[new Date().getDay()];
  }
  return WEEKDAY_NAMES[parsed.getDay()];
};

const getFallbackServiceId = (services) => (
  services.find((service) => service.name?.toLowerCase().includes('main'))?.id ||
  services[0]?.id ||
  1
);

const getScheduledServiceId = (services, dateString) => {
  if (!services.length) return 1;

  const weekday = normalizeDay(getWeekdayNameForDate(dateString));
  const scheduledService = services.find(
    (service) => normalizeDay(service.default_day) === weekday
  );

  return scheduledService?.id || getFallbackServiceId(services);
};

const LEADER_CORE_CACHE_PREFIX = 'leader-core-cache';

const getLeaderCoreCacheKey = (leaderId) => `${LEADER_CORE_CACHE_PREFIX}:${leaderId || 'default'}`;

const readLeaderCoreCache = (leaderId) => {
  try {
    const cached = localStorage.getItem(getLeaderCoreCacheKey(leaderId)) ||
      localStorage.getItem(getLeaderCoreCacheKey('latest'));
    return cached ? JSON.parse(cached) : null;
  } catch (error) {
    console.warn('Failed to read offline leader cache:', error);
    return null;
  }
};

const writeLeaderCoreCache = (leaderId, snapshot) => {
  try {
    const serialized = JSON.stringify({ ...snapshot, cached_at: new Date().toISOString() });
    localStorage.setItem(getLeaderCoreCacheKey(leaderId), serialized);
    localStorage.setItem(getLeaderCoreCacheKey('latest'), serialized);
  } catch (error) {
    console.warn('Failed to save offline leader cache:', error);
  }
};

const useLeaderData = () => {
  const { isOnline, queueSubmission, syncPending } = useOffline();
  const { user } = useAuth();

  // Section & Members
  const [sectionInfo, setSectionInfo] = useState(null);
  const [members, setMembers] = useState([]);
  const [isHead, setIsHead] = useState(false);
  const [loading, setLoading] = useState(true);
  const [sectionLeaders, setSectionLeaders] = useState([]);
  const [attendanceLeaderId, setAttendanceLeaderId] = useState(null);
  const [attendanceLeaderName, setAttendanceLeaderName] = useState('');
  const [actingOnBehalf, setActingOnBehalf] = useState(false);

  const [serviceTypes, setServiceTypes] = useState([]);
  const [selectedServiceId, setSelectedServiceId] = useState(1);
  const [attendance, setAttendance] = useState({});
  const [selectedDate, setSelectedDate] = useState(() => formatLocalDate());
  const [submitted, setSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [isUnauthorized, setIsUnauthorized] = useState(false);
  const [leaderAssignments, setLeaderAssignments] = useState([]);

  // History
  const [history, setHistory] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(true);

  // Section Overview (head leaders)
  const [overviewData, setOverviewData] = useState(null);
  const [overviewLoading, setOverviewLoading] = useState(false);

  // Reports / Trends
  const [trendsData, setTrendsData] = useState([]);
  const [trendsLoading, setTrendsLoading] = useState(false);
  const [trendsRange, setTrendsRange] = useState({ start: '', end: '' });

  // Member management
  const [editingMember, setEditingMember] = useState(null);
  const [isMemberModalOpen, setIsMemberModalOpen] = useState(false);
  const [deletingMember, setDeletingMember] = useState(null);
  const [autogeneratedId, setAutogeneratedId] = useState('');
  const [saving, setSaving] = useState(false);

  // Toast message
  const [message, setMessage] = useState('');

  // Absent follow-ups
  const [consecutiveAbsences, setConsecutiveAbsences] = useState([]);
  const [followUps, setFollowUps] = useState([]);

  const messageTimerRef = useRef(null);
  const serviceSelectionWasManualRef = useRef(false);
  const previousSelectedDateRef = useRef(selectedDate);
  const showMessage = useCallback((msg, duration = 4000) => {
    setMessage(msg);
    if (messageTimerRef.current) clearTimeout(messageTimerRef.current);
    messageTimerRef.current = setTimeout(() => setMessage(''), duration);
  }, []);

  // --- Data Loaders ---
  // Eligibility Filter Helper
  const checkEligibility = useCallback((member, service) => {
    if (!service) return true;
    const rules = service.eligibility_rules || {};
    
    // Opt-out check
    if (member.opt_out_services) {
      try {
        const optOuts = JSON.parse(member.opt_out_services);
        if (optOuts.includes(service.id)) return false;
      } catch (e) { /* noop */ }
    }

    // Gender check
    if (rules.gender && member.gender && rules.gender !== 'All' && member.gender !== rules.gender) return false;
    
    // Section check
    if (rules.sections && rules.sections.length > 0) {
      if (!rules.sections.includes(member.section_id)) return false;
    }
    
    // Role check
    if (rules.role && rules.role !== 'All') {
      const isLeader = member.role === 'Leader' || member.is_leader;
      if (rules.role === 'Leader' && !isLeader) return false;
    }
    
    // Age check
    if (rules.age_range && member.date_of_birth) {
      const birthDate = new Date(member.date_of_birth);
      let age = new Date().getFullYear() - birthDate.getFullYear();
      const m = new Date().getMonth() - birthDate.getMonth();
      if (m < 0 || (m === 0 && new Date().getDate() < birthDate.getDate())) age--;
      
      const { min, max } = rules.age_range;
      if (min && age < min) return false;
      if (max && age > max) return false;
    }

    return true;
  }, []);

  const eligibleMembers = members.filter(m => 
    checkEligibility(m, serviceTypes.find(s => s.id === selectedServiceId))
  );

  // --- Data Loaders ---
  const loadMembers = useCallback(async () => {
    if (user?.is_new_member_leader) {
      setLoading(false);
      return;
    }
    setLoading(true);
    try {
      const [membersRes, servicesRes] = await Promise.all([
        leaderAPI.getMembers(attendanceLeaderId),
        leaderAPI.getServiceTypes()
      ]);

      const snapshot = {
        sectionInfo: {
          section_id: membersRes.data.section_id,
          name: membersRes.data.section_name,
          leader_id: membersRes.data.leader_id,
          leader: membersRes.data.leader_name,
        },
        members: membersRes.data.members,
        isHead: Boolean(membersRes.data.is_head),
        sectionLeaders: membersRes.data.section_leaders || [],
        attendanceLeaderId: membersRes.data.attendance_leader_id,
        attendanceLeaderName: membersRes.data.attendance_leader_name || membersRes.data.leader_name,
        actingOnBehalf: Boolean(membersRes.data.acting_on_behalf),
        serviceTypes: servicesRes.data,
      };

      setSectionInfo(snapshot.sectionInfo);
      setMembers(snapshot.members);
      setIsHead(snapshot.isHead);
      setSectionLeaders(snapshot.sectionLeaders);
      setAttendanceLeaderId((current) => current || snapshot.attendanceLeaderId);
      setAttendanceLeaderName(snapshot.attendanceLeaderName);
      setActingOnBehalf(snapshot.actingOnBehalf);
      setServiceTypes(snapshot.serviceTypes);
      setAttendance({});
      writeLeaderCoreCache(snapshot.attendanceLeaderId || attendanceLeaderId, snapshot);
    } catch (error) {
      console.error('Failed to load leader core data:', error);
      const cached = readLeaderCoreCache(attendanceLeaderId);
      if (cached) {
        setSectionInfo(cached.sectionInfo);
        setMembers(cached.members || []);
        setIsHead(Boolean(cached.isHead));
        setSectionLeaders(cached.sectionLeaders || []);
        setAttendanceLeaderId((current) => current || cached.attendanceLeaderId);
        setAttendanceLeaderName(cached.attendanceLeaderName || cached.sectionInfo?.leader || '');
        setActingOnBehalf(Boolean(cached.actingOnBehalf));
        setServiceTypes(cached.serviceTypes || []);
        showMessage('Offline roster loaded. You can mark attendance and sync later.', 6000);
      } else {
        showMessage('No offline roster found. Open this page once while online before using it offline.', 7000);
      }
    } finally {
      setLoading(false);
    }
  }, [attendanceLeaderId, showMessage, user?.is_new_member_leader]);

  const handleAttendanceLeaderSelection = useCallback((leaderId) => {
    setAttendanceLeaderId(leaderId ? Number(leaderId) : null);
    setAttendance({});
    setSubmitted(false);
  }, []);

  const loadAssignments = useCallback(async () => {
    if (user?.is_new_member_leader) return;
    try {
      const response = await leaderAPI.getAssignments();
      setLeaderAssignments(response.data);
    } catch (error) {
      console.error('Failed to load leader assignments:', error);
    }
  }, [user?.is_new_member_leader]);

  const loadHistory = useCallback(async () => {
    if (user?.is_new_member_leader) {
      setHistoryLoading(false);
      return;
    }
    setHistoryLoading(true);
    try {
      const response = await leaderAPI.getHistory();
      setHistory(response.data);
    } catch (error) {
      console.error('Failed to load history:', error);
    } finally {
      setHistoryLoading(false);
    }
  }, [user?.is_new_member_leader]);

  const loadOverview = useCallback(async () => {
    if (user?.is_new_member_leader) {
      setOverviewLoading(false);
      return;
    }
    setOverviewLoading(true);
    try {
      const response = await leaderAPI.getSectionOverview(selectedDate, selectedServiceId);
      setOverviewData(response.data);
    } catch (error) {
      console.error('Failed to load section overview:', error);
    } finally {
      setOverviewLoading(false);
    }
  }, [selectedDate, selectedServiceId, user?.is_new_member_leader]);

  const loadTrends = useCallback(async () => {
    if (user?.is_new_member_leader) {
      setTrendsLoading(false);
      return;
    }
    setTrendsLoading(true);
    try {
      const response = await leaderAPI.getAttendanceTrends(90);
      setTrendsData(response.data.trends);
      setTrendsRange(response.data.date_range);
    } catch (error) {
      console.error('Failed to load attendance trends:', error);
    } finally {
      setTrendsLoading(false);
    }
  }, [user?.is_new_member_leader]);

  const loadConsecutiveAbsences = useCallback(async () => {
    if (user?.is_new_member_leader) return;
    try {
      const response = await leaderAPI.getConsecutiveAbsences();
      setConsecutiveAbsences(response.data);
    } catch (error) {
      console.error('Failed to load consecutive absences:', error);
    }
  }, [user?.is_new_member_leader]);

  const loadFollowUps = useCallback(async () => {
    if (user?.is_new_member_leader) return;
    try {
      const response = await leaderAPI.getFollowUps();
      setFollowUps(response.data);
    } catch (error) {
      console.error('Failed to load follow-ups:', error);
    }
  }, [user?.is_new_member_leader]);

  const handleUpdateFollowUp = useCallback(async (memberId, data) => {
    await leaderAPI.updateFollowUp(memberId, data);
    showMessage('Follow-up saved');
    await loadFollowUps();
    await loadConsecutiveAbsences();
  }, [loadFollowUps, loadConsecutiveAbsences, showMessage]);

  const handleDateSelection = useCallback((nextDate) => {
    previousSelectedDateRef.current = nextDate;
    serviceSelectionWasManualRef.current = false;
    setSelectedDate(nextDate);

    if (!serviceTypes.length) return;

    const nextServiceId = getScheduledServiceId(serviceTypes, nextDate);
    setSelectedServiceId((currentId) => (
      currentId === nextServiceId ? currentId : nextServiceId
    ));
  }, [serviceTypes]);

  const handleServiceSelection = useCallback((serviceId) => {
    serviceSelectionWasManualRef.current = true;
    setSelectedServiceId(serviceId);
  }, []);

  const checkSubmission = useCallback(async () => {
    try {
      const response = await leaderAPI.getAttendanceStatus(selectedDate, selectedServiceId, attendanceLeaderId);
      if (response.data.unauthorized) {
        setIsUnauthorized(true);
        setSubmitted(false);
        setAttendance({});
        return;
      }
      setIsUnauthorized(false);
      setSubmitted(response.data.submitted);
      if (response.data.attendance && response.data.attendance.length > 0) {
        const existing = {};
        response.data.attendance.forEach((a) => {
          existing[a.member_id] = a.status;
        });
        setAttendance(existing);
      } else {
        setAttendance({});
      }
    } catch (error) {
      console.error('Failed to check submission:', error);
    }
  }, [selectedDate, selectedServiceId, attendanceLeaderId]);

  // --- Attendance Handlers ---
  const handleStatusChange = useCallback(
    (memberId, status) => {
      if (submitted) return;
      setAttendance((prev) => ({ ...prev, [memberId]: status }));
    },
    [submitted]
  );

  const [submitError, setSubmitError] = useState('');
  const [queuedForDate, setQueuedForDate] = useState(null);

  const handleSubmit = useCallback(async () => {
    setSubmitError('');
    if (submitted) {
      setSubmitError('Attendance already submitted for this date');
      return false;
    }
    if (Object.keys(attendance).length !== eligibleMembers.length) {
      setSubmitError(
        `Please mark attendance for all eligible members before submitting. You have marked ${Object.keys(attendance).length} out of ${eligibleMembers.length}.`
      );
      return false;
    }

    setSubmitting(true);
    try {
      const attendanceArray = Object.entries(attendance).map(
        ([member_id, status]) => ({
          member_id: parseInt(member_id),
          status,
        })
      );

      if (!isOnline) {
        if (actingOnBehalf) {
          setSubmitError('Please reconnect before submitting attendance on behalf of another leader.');
          return false;
        }
        const result = await queueSubmission({
          date: selectedDate,
          service_id: selectedServiceId,
          attendance: attendanceArray,
          leader_id: sectionInfo?.leader_id,
          section_id: sectionInfo?.section_id
        });
        if (result.success) {
          setQueuedForDate(selectedDate);
          setSubmitted(true);
          showMessage('Attendance saved offline — will sync when you reconnect');
          return true;
        } else if (result.reason === 'already_queued') {
          setSubmitError('Attendance already queued for this date');
          return false;
        }
        return false;
      }

      await leaderAPI.submitAttendance(selectedDate, attendanceArray, selectedServiceId, attendanceLeaderId);
      setSubmitted(true);
      loadHistory();
      showMessage('Attendance submitted successfully!');
      return true;
    } catch (error) {
      setSubmitError(
        error.response?.data?.error || error.message
      );
      return false;
    } finally {
      setSubmitting(false);
    }
  }, [submitted, attendance, eligibleMembers.length, selectedDate, selectedServiceId, attendanceLeaderId, actingOnBehalf, sectionInfo, loadHistory, showMessage, isOnline, queueSubmission]);

  // --- Member CRUD Handlers ---
  const openAddMember = useCallback(() => {
    setEditingMember(null);
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let newId = 'MEM-';
    for (let i = 0; i < 8; i++)
      newId += chars.charAt(Math.floor(Math.random() * chars.length));
    setAutogeneratedId(newId);
    setIsMemberModalOpen(true);
  }, []);

  const openEditMember = useCallback((member) => {
    setEditingMember(member);
    setIsMemberModalOpen(true);
  }, []);

  const handleMemberSave = useCallback(
    async (e) => {
      e.preventDefault();
      const formData = new FormData(e.target);
      const memberData = {
        membership_id: formData.get('membership_id'),
        full_name: formData.get('full_name'),
        phone: formData.get('phone'),
        email: formData.get('email'),
        gender: formData.get('gender'),
        age_group: formData.get('age_group'),
      };

      setSaving(true);
      try {
        if (editingMember) {
          await leaderAPI.updateMember(editingMember.id, memberData);
          showMessage('Member updated successfully');
        } else {
          await leaderAPI.createMember(memberData);
          showMessage('Member added successfully');
        }
        setIsMemberModalOpen(false);
        setEditingMember(null);
        loadMembers();
      } catch (error) {
        showMessage(
          `Error saving member: ${error.response?.data?.error || error.message}`
        );
      } finally {
        setSaving(false);
      }
    },
    [editingMember, loadMembers, showMessage]
  );

  const handleMemberDelete = useCallback(async () => {
    if (!deletingMember) return;
    setSaving(true);
    try {
      await leaderAPI.deleteMember(deletingMember.id);
      showMessage('Member deleted successfully');
      setDeletingMember(null);
      loadMembers();
    } catch (error) {
      showMessage(
        `Error deleting member: ${error.response?.data?.error || error.message}`
      );
    } finally {
      setSaving(false);
    }
  }, [deletingMember, loadMembers, showMessage]);

  // --- Initial Load ---
  useEffect(() => {
    if (user?.is_new_member_leader) {
      setLoading(false);
      setHistoryLoading(false);
      return;
    }
    loadMembers();
    loadHistory();
    loadConsecutiveAbsences();
    loadFollowUps();
    loadAssignments();
  }, [user?.is_new_member_leader, loadMembers, loadHistory, loadConsecutiveAbsences, loadFollowUps, loadAssignments]);

  useEffect(() => {
    if (selectedDate !== previousSelectedDateRef.current) {
      previousSelectedDateRef.current = selectedDate;
      serviceSelectionWasManualRef.current = false;
    }
  }, [selectedDate]);

  useEffect(() => {
    if (!serviceTypes.length || serviceSelectionWasManualRef.current) return;

    const nextServiceId = getScheduledServiceId(serviceTypes, selectedDate);
    setSelectedServiceId((currentId) => (
      currentId === nextServiceId ? currentId : nextServiceId
    ));
  }, [serviceTypes, selectedDate]);

  useEffect(() => {
    checkSubmission();
  }, [checkSubmission, selectedServiceId]);

  useEffect(() => {
    if (!isOnline) {
      getQueuedSubmissionForDate(selectedDate, selectedServiceId).then((record) => {
        if (record) {
          setQueuedForDate(selectedDate);
          setSubmitted(true);
          const existing = {};
          record.attendance.forEach((a) => {
            existing[a.member_id] = a.status;
          });
          setAttendance(existing);
        } else {
          setQueuedForDate(null);
        }
      });
    }
  }, [selectedDate, selectedServiceId, isOnline]);

  useEffect(() => {
    if (isOnline) {
      syncPending(async (record) => {
        const syncedServiceId = record.service_id || getScheduledServiceId(serviceTypes, record.date);
        await leaderAPI.submitAttendance(record.date, record.attendance, syncedServiceId);
      }).then((result) => {
        if (result.synced > 0) {
          showMessage(`${result.synced} offline attendance submission(s) synced successfully`);
          loadHistory();
          checkSubmission();
        }
        if (result.conflicts > 0) {
          showMessage(`${result.conflicts} record(s) had conflicts — check sync status`, 6000);
        }
        if (result.failed > 0) {
          showMessage(`${result.failed} offline submission(s) could not sync. Keep the app open online and try refresh.`, 7000);
        }
      });
    }
  }, [isOnline, serviceTypes, syncPending, showMessage, loadHistory, checkSubmission]);

  return {
    // Section info
    sectionInfo,
    isHead,
    loading,
    // Members
    members,
    // Attendance
    attendance,
    selectedDate,
    setSelectedDate,
    handleDateSelection,
    submitted,
    submitting,
    isOnline,
    isUnauthorized,
    leaderAssignments,
    sectionLeaders,
    attendanceLeaderId,
    attendanceLeaderName,
    actingOnBehalf,
    handleAttendanceLeaderSelection,
    handleStatusChange,
    handleSubmit,
    queuedForDate,
    submitError,
    // History
    history,
    historyLoading,
    loadHistory,
    // Overview (head)
    overviewData,
    overviewLoading,
    loadOverview,
    // Trends
    trendsData,
    trendsLoading,
    trendsRange,
    loadTrends,
    // Member management
    editingMember,
    isMemberModalOpen,
    setIsMemberModalOpen,
    deletingMember,
    setDeletingMember,
    autogeneratedId,
    saving,
    openAddMember,
    openEditMember,
    handleMemberSave,
    handleMemberDelete,
    // Message
    message,
    showMessage,
    // Refresh
    loadMembers,
    eligibleMembers,
    // Service Types
    serviceTypes,
    selectedServiceId,
    setSelectedServiceId,
    handleServiceSelection,
    // Absent follow-ups
    consecutiveAbsences,
    followUps,
    handleUpdateFollowUp,
  };
};

export default useLeaderData;
