import React, { useState, useCallback, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import useLeaderData from '../hooks/useLeaderData';
import { CheckCircle2 } from 'lucide-react';
import useOffline from '../hooks/useOffline';
import SettingsView from '../components/admin/SettingsView';

import LeaderOverview from '../components/leader/LeaderOverview';
import TakeAttendance from '../components/leader/TakeAttendance';
import LeaderMembers from '../components/leader/LeaderMembers';
import LeaderHistory from '../components/leader/LeaderHistory';
import LeaderReports from '../components/leader/LeaderReports';
import LeaderOutreach from '../components/leader/LeaderOutreach';
import SectionOverview from '../components/leader/SectionOverview';
import ConflictResolutionModal from '../components/leader/ConflictResolutionModal';
import ChurchCalendar from '../components/ChurchCalendar';
import HomeCellMembers from '../components/leader/HomeCellMembers';
import NewMemberLeaderView from '../components/admin/NewMemberLeaderView';

const LeaderDashboard = () => {
  const { tab } = useParams();
  const navigate = useNavigate();
  const activeTab = tab || 'dashboard';
  const data = useLeaderData();
  const { conflicts, resolveConflict } = useOffline();
  const [showConflicts, setShowConflicts] = useState(false);
  const [settingsToast, setSettingsToast] = useState(null);

  const showMessage = useCallback((msg) => {
    setSettingsToast(msg);
    setTimeout(() => setSettingsToast(null), 3000);
  }, []);

  // Load trends when reports tab is active
  useEffect(() => {
    if (activeTab === 'reports') {
      data.loadTrends();
    }
  }, [activeTab]);

  // Load overview when overview tab is active (for head leaders)
  useEffect(() => {
    if (activeTab === 'overview' && data.isHead) {
      data.loadOverview();
    }
  }, [activeTab, data.isHead, data.selectedDate, data.selectedServiceId]);

  if (data.loading) {
    return (
      <div className="space-y-4 animate-fade-in">
        <div className="skeleton h-24 rounded-2xl" />
        <div className="grid grid-cols-2 gap-4">
          <div className="skeleton h-32 rounded-2xl" />
          <div className="skeleton h-32 rounded-2xl" />
        </div>
      </div>
    );
  }

  const handleSubmitAndRedirect = async () => {
    const success = await data.handleSubmit();
    if (success) {
      alert('Attendance submitted successfully!');
      navigate('/leader');
    }
  };

  // Tab-to-component mapping
  const renderTab = () => {
    switch (activeTab) {
      case 'dashboard':
        return (
          <LeaderOverview
            members={data.members}
            eligibleMembers={data.eligibleMembers}
            history={data.history}
            attendance={data.attendance}
            submitted={data.submitted}
            serviceTypes={data.serviceTypes}
            selectedServiceId={data.selectedServiceId}
            leaderName={data.sectionInfo?.leader}
            onGoToAttendance={() => navigate('/leader/attendance')}
          />
        );

      case 'attendance':
        return (
          <TakeAttendance
            members={data.eligibleMembers}
            attendance={data.attendance}
            selectedDate={data.selectedDate}
            setSelectedDate={data.handleDateSelection}
            serviceTypes={data.serviceTypes}
            selectedServiceId={data.selectedServiceId}
            onServiceChange={data.handleServiceSelection}
            submitted={data.submitted}
            submitting={data.submitting}
            submitError={data.submitError}
            isUnauthorized={data.isUnauthorized}
            leaderAssignments={data.leaderAssignments}
            isHead={data.isHead}
            sectionLeaders={data.sectionLeaders}
            attendanceLeaderId={data.attendanceLeaderId}
            attendanceLeaderName={data.attendanceLeaderName}
            actingOnBehalf={data.actingOnBehalf}
            onAttendanceLeaderChange={data.handleAttendanceLeaderSelection}
            onStatusChange={data.handleStatusChange}
            onSubmit={handleSubmitAndRedirect}
            isOnline={data.isOnline}
            queuedForDate={data.queuedForDate}
          />
        );

      case 'calendar':
        return <ChurchCalendar />;

      case 'members':
        return (
          <LeaderMembers
            members={data.members}
            isHead={data.isHead}
            editingMember={data.editingMember}
            isMemberModalOpen={data.isMemberModalOpen}
            setIsMemberModalOpen={data.setIsMemberModalOpen}
            deletingMember={data.deletingMember}
            setDeletingMember={data.setDeletingMember}
            autogeneratedId={data.autogeneratedId}
            saving={data.saving}
            onAdd={data.openAddMember}
            onEdit={data.openEditMember}
            onSave={data.handleMemberSave}
            onDelete={data.handleMemberDelete}
            consecutiveAbsences={data.consecutiveAbsences}
            followUps={data.followUps}
            onUpdateFollowUp={data.handleUpdateFollowUp}
          />
        );

      case 'home-cells':
        return <HomeCellMembers />;

      case 'history':
        return (
          <LeaderHistory
            history={data.history}
            historyLoading={data.historyLoading}
            isHead={data.isHead}
          />
        );

      case 'reports':
        return (
          <LeaderReports
            trendsData={data.trendsData}
            trendsLoading={data.trendsLoading}
            loadTrends={data.loadTrends}
          />
        );

      case 'outreach':
        return <LeaderOutreach members={data.members} />;

      case 'new-members':
        return <NewMemberLeaderView />;

      case 'settings':
        return (
          <div>
            {settingsToast && (
              <div className="toast-success mb-6">
                <span>{settingsToast}</span>
              </div>
            )}
            <SettingsView
              leaders={[]}
              loadCoreData={() => {}}
              loadLeaders={() => {}}
              showMessage={showMessage}
            />
          </div>
        );

      case 'overview':
        if (!data.isHead) {
          return (
            <LeaderOverview
              members={data.members}
              eligibleMembers={data.eligibleMembers}
              history={data.history}
              attendance={data.attendance}
              submitted={data.submitted}
              serviceTypes={data.serviceTypes}
              selectedServiceId={data.selectedServiceId}
              leaderName={data.sectionInfo?.leader}
              onGoToAttendance={() => navigate('/leader/attendance')}
            />
          );
        }
        return (
          <SectionOverview
            selectedDate={data.selectedDate}
            setSelectedDate={data.handleDateSelection}
            serviceTypes={data.serviceTypes}
            selectedServiceId={data.selectedServiceId}
            onServiceChange={data.handleServiceSelection}
            sectionName={data.sectionInfo?.name}
            overviewData={data.overviewData}
            overviewLoading={data.overviewLoading}
            loadOverview={data.loadOverview}
          />
        );

      default:
        return (
          <LeaderOverview
            members={data.members}
            eligibleMembers={data.eligibleMembers}
            history={data.history}
            attendance={data.attendance}
            submitted={data.submitted}
            serviceTypes={data.serviceTypes}
            selectedServiceId={data.selectedServiceId}
            leaderName={data.sectionInfo?.leader}
            onGoToAttendance={() => navigate('/leader/attendance')}
          />
        );
    }
  };

  return (
    <>
      {/* Toast Message */}
      {data.message && (
        <div className="toast-success mb-6">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
          <span>{data.message}</span>
        </div>
      )}

      {/* Active Tab Content */}
      {renderTab()}

      {/* Conflict Resolution Modal */}
      {showConflicts && (
        <ConflictResolutionModal
          conflicts={conflicts}
          onResolve={(id, action) => {
            resolveConflict(id, action);
            setShowConflicts((prev) => {
              const remaining = conflicts.filter((c) => c.id !== id);
              return remaining.length > 0;
            });
          }}
          onClose={() => setShowConflicts(false)}
        />
      )}
    </>
  );
};

export default LeaderDashboard;
