const sqlite3 = require('sqlite3').verbose();
const path = require('path');
const dotenv = require('dotenv');
dotenv.config();

const usePostgres = String(process.env.DB_CLIENT || '').toLowerCase() === 'postgres';
console.log('usePostgres:', usePostgres);

let db;
let run;
let all;
let get;

if (usePostgres) {
  const { Pool } = require('pg');
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  db = pool;
  run = (sql, params = []) => pool.query(sql, params).then(res => ({ lastID: null, changes: res.rowCount }));
  all = (sql, params = []) => pool.query(sql, params).then(res => res.rows);
  get = (sql, params = []) => pool.query(sql, params).then(res => res.rows[0]);
} else {
  const dbPath = process.env.DB_PATH || path.join(__dirname, 'database.sqlite');
  const sqliteDb = new sqlite3.Database(dbPath);
  db = sqliteDb;
  run = (sql, params = []) => new Promise((resolve, reject) => {
    sqliteDb.run(sql, params, function(err) {
      if (err) reject(err);
      else resolve({ lastID: this.lastID, changes: this.changes });
    });
  });
  all = (sql, params = []) => new Promise((resolve, reject) => {
    sqliteDb.all(sql, params, (err, rows) => {
      if (err) reject(err);
      else resolve(rows);
    });
  });
  get = (sql, params = []) => new Promise((resolve, reject) => {
    sqliteDb.get(sql, params, (err, row) => {
      if (err) reject(err);
      else resolve(row);
    });
  });
}

async function migrate() {
  try {
    // 1. Get all current rows
    const rows = await all('SELECT * FROM home_cell_leaders');
    console.log(`Found ${rows.length} existing leader assignments to migrate.`);
    
    const migratedRows = [];
    for (const row of rows) {
      // Find member_id of the leader
      const leader = await get(`
        SELECT u.member_id 
        FROM leaders l
        JOIN users u ON l.user_id = u.id
        WHERE l.id = ?
      `, [row.leader_id]);
      
      if (leader && leader.member_id) {
        migratedRows.push({ cell_id: row.cell_id, leader_id: leader.member_id });
      }
    }
    console.log(`Mapped ${migratedRows.length} assignments to member IDs.`);

    // 2. Re-create the table with correct foreign key referencing members(id)
    await run('DROP TABLE IF EXISTS home_cell_leaders');
    
    if (usePostgres) {
      await run(`
        CREATE TABLE home_cell_leaders (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          cell_id INTEGER NOT NULL REFERENCES home_cells(id) ON DELETE CASCADE,
          leader_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
          assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
          UNIQUE(cell_id, leader_id)
        )
      `);
    } else {
      await run(`
        CREATE TABLE home_cell_leaders (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          cell_id INTEGER NOT NULL,
          leader_id INTEGER NOT NULL,
          assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
          UNIQUE(cell_id, leader_id),
          FOREIGN KEY (cell_id) REFERENCES home_cells(id) ON DELETE CASCADE,
          FOREIGN KEY (leader_id) REFERENCES members(id) ON DELETE CASCADE
        )
      `);
    }
    console.log('Re-created home_cell_leaders table referencing members(id).');

    // 3. Re-insert migrated rows
    for (const row of migratedRows) {
      try {
        await run('INSERT INTO home_cell_leaders (cell_id, leader_id) VALUES (?, ?)', [row.cell_id, row.leader_id]);
      } catch (e) {
        console.warn('Skipped duplicate or invalid entry:', e.message);
      }
    }
    console.log('Migration completed successfully.');
    
    if (usePostgres) {
      await db.end();
    } else {
      db.close();
    }
  } catch (e) {
    console.error('Migration failed:', e);
    process.exit(1);
  }
}

migrate();
