BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'leader', 'pastor')),
  full_name TEXT NOT NULL,
  profile_picture TEXT,
  totp_secret TEXT,
  totp_enabled INTEGER DEFAULT 0,
  backup_codes TEXT,
  failed_login_attempts INTEGER DEFAULT 0,
  locked_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leaders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  section_id INTEGER NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  phone TEXT,
  email TEXT,
  is_head INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, section_id)
);

CREATE TABLE IF NOT EXISTS members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membership_id TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  section_id INTEGER NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  leader_id INTEGER NOT NULL REFERENCES leaders(id) ON DELETE CASCADE,
  phone TEXT,
  email TEXT,
  gender TEXT,
  date_of_birth DATE,
  age_group TEXT,
  show_age_to_leaders INTEGER DEFAULT 0,
  hide_from_birthday_list INTEGER DEFAULT 0,
  opt_out_services TEXT DEFAULT '[]',
  visitor_date DATE,
  address TEXT,
  status TEXT DEFAULT 'Active',
  flags TEXT DEFAULT '[]',
  last_contacted_at TIMESTAMPTZ,
  last_contacted_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  prayer_requests TEXT DEFAULT '[]',
  is_active INTEGER DEFAULT 1,
  hall_of_fame_points INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  default_day TEXT,
  default_time TEXT,
  eligibility_rules TEXT,
  points_config TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('present', 'absent', 'excused')),
  submitted_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service_type_id INTEGER REFERENCES service_types(id) ON DELETE SET NULL,
  service_type TEXT DEFAULT 'main',
  submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (member_id, date)
);

CREATE TABLE IF NOT EXISTS submission_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leader_id INTEGER NOT NULL REFERENCES leaders(id) ON DELETE CASCADE,
  section_id INTEGER NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  service_id INTEGER REFERENCES service_types(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (leader_id, date, service_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('missed_submission', 'absent_member', 'attendance_drop', 'system')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  entity_type TEXT,
  entity_id INTEGER,
  is_read INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS announcements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  audience TEXT NOT NULL DEFAULT 'all',
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal', 'important', 'urgent')),
  scheduled_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'archived')),
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_followup_tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_type TEXT NOT NULL CHECK (person_type IN ('Member', 'Visitor')),
  person_id INTEGER,
  full_name TEXT NOT NULL,
  section_name TEXT,
  reason TEXT,
  owner_id INTEGER REFERENCES leaders(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done')),
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visitor_intake (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  section_interest TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'converted', 'archived')),
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS church_calendar_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  event_date DATE NOT NULL,
  event_time TEXT,
  event_type TEXT NOT NULL DEFAULT 'service',
  role_title TEXT,
  assigned_to TEXT,
  section_name TEXT,
  location TEXT,
  notes TEXT,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS absent_followups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  leader_id INTEGER NOT NULL REFERENCES leaders(id) ON DELETE CASCADE,
  absence_date DATE NOT NULL,
  contacted INTEGER DEFAULT 0,
  contact_method TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id INTEGER,
  old_value TEXT,
  new_value TEXT,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_instances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id INTEGER NOT NULL REFERENCES service_types(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  assigned_leader_ids TEXT DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (service_id, date)
);

CREATE TABLE IF NOT EXISTS offline_attendance_imports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id TEXT UNIQUE NOT NULL,
  package_checksum TEXT NOT NULL,
  leader_id INTEGER REFERENCES leaders(id) ON DELETE SET NULL,
  section_id INTEGER REFERENCES sections(id) ON DELETE SET NULL,
  service_id INTEGER REFERENCES service_types(id) ON DELETE SET NULL,
  attendance_date DATE NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('admin_upload', 'leader_sync')),
  imported_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  status TEXT NOT NULL,
  original_filename TEXT,
  summary_json TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS home_cells (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  cell_number INTEGER UNIQUE NOT NULL,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS home_cell_leaders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cell_id INTEGER NOT NULL REFERENCES home_cells(id) ON DELETE CASCADE,
  leader_id INTEGER NOT NULL REFERENCES leaders(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (cell_id, leader_id)
);

CREATE TABLE IF NOT EXISTS home_cell_members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cell_id INTEGER NOT NULL REFERENCES home_cells(id) ON DELETE CASCADE,
  church_member_id INTEGER REFERENCES members(id) ON DELETE SET NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  address TEXT,
  duplicate_key TEXT UNIQUE NOT NULL,
  added_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS outreach_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leader_id INTEGER NOT NULL REFERENCES leaders(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  contact_method TEXT NOT NULL CHECK (contact_method IN ('Call', 'WhatsApp', 'SMS', 'Visit', 'Prayer', 'Counseling', 'Hospital Visit', 'Other', 'sms', 'whatsapp', 'phone', 'email', 'visit', 'other')),
  outcome TEXT,
  service_id INTEGER REFERENCES service_types(id) ON DELETE SET NULL,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  message TEXT,
  week_start DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scheduled_reminders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('submission_reminder', 'follow_up_reminder', 'birthday_greeting', 'weekly_summary')),
  entity_type TEXT,
  entity_id INTEGER,
  scheduled_for TIMESTAMPTZ NOT NULL,
  sent INTEGER DEFAULT 0,
  sent_at TIMESTAMPTZ,
  payload TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pastoral_care_queue (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  assigned_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  assigned_to INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  due_date DATE NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'cancelled')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hall_of_fame_adjustments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  points INTEGER NOT NULL,
  reason TEXT NOT NULL,
  outreach_log_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_members_section ON members(section_id);
CREATE INDEX IF NOT EXISTS idx_members_leader ON members(leader_id);
CREATE INDEX IF NOT EXISTS idx_members_active_section ON members(is_active, section_id);
CREATE INDEX IF NOT EXISTS idx_members_birthdays ON members(date_of_birth) WHERE date_of_birth IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(date);
CREATE INDEX IF NOT EXISTS idx_attendance_member_date ON attendance(member_id, date);
CREATE INDEX IF NOT EXISTS idx_attendance_service_date ON attendance(service_type_id, date);
CREATE INDEX IF NOT EXISTS idx_attendance_status ON attendance(status);
CREATE INDEX IF NOT EXISTS idx_submission_service ON submission_log(service_id);
CREATE INDEX IF NOT EXISTS idx_submission_date_service ON submission_log(date, service_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_announcements_status ON announcements(status, created_at);
CREATE INDEX IF NOT EXISTS idx_followup_tasks_status ON admin_followup_tasks(status, created_at);
CREATE INDEX IF NOT EXISTS idx_visitor_intake_status ON visitor_intake(status, created_at);
CREATE INDEX IF NOT EXISTS idx_church_calendar_date ON church_calendar_events(event_date);
CREATE INDEX IF NOT EXISTS idx_followups_member ON absent_followups(member_id);
CREATE INDEX IF NOT EXISTS idx_followups_leader ON absent_followups(leader_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_outreach_leader ON outreach_logs(leader_id);
CREATE INDEX IF NOT EXISTS idx_outreach_member ON outreach_logs(member_id);
CREATE INDEX IF NOT EXISTS idx_outreach_week ON outreach_logs(week_start);
CREATE INDEX IF NOT EXISTS idx_outreach_leader_week ON outreach_logs(leader_id, week_start);
CREATE INDEX IF NOT EXISTS idx_reminders_scheduled ON scheduled_reminders(scheduled_for, sent);
CREATE INDEX IF NOT EXISTS idx_reminders_type ON scheduled_reminders(type);

INSERT INTO settings (key, value)
VALUES
  ('points_attendance', '10'),
  ('points_excused', '3'),
  ('midweek_day', 'Wednesday')
ON CONFLICT (key) DO NOTHING;

INSERT INTO service_types (id, name, default_day, eligibility_rules, points_config)
VALUES
  (1, 'Main Service', 'Sunday', '{}', '{"present":10,"excused":3}'),
  (2, 'Leaders Gathering', 'Tuesday', '{"roles":["admin","leader"]}', '{"present":5,"excused":3}'),
  (3, 'Youth Service', 'Wednesday', '{"sections":["Youth"],"age_range":[13,25]}', '{"present":5,"excused":3}'),
  (4, 'Women''s Service', 'Thursday', '{"gender":"Female","sections":["Women''s Ministry"]}', '{"present":5,"excused":3}'),
  (5, 'Prayer Service', 'Friday', '{}', '{"present":5,"excused":3}'),
  (6, 'Home Cell', 'Tuesday', '{"home_cells":true}', '{"present":5,"excused":3}')
ON CONFLICT (id) DO NOTHING;

INSERT INTO home_cells (name, cell_number)
VALUES
  ('Home Cell 1', 1),
  ('Home Cell 2', 2),
  ('Home Cell 3', 3),
  ('Home Cell 4', 4),
  ('Home Cell 5', 5)
ON CONFLICT (cell_number) DO NOTHING;

INSERT INTO schema_migrations (name)
VALUES ('001_initial_postgres_schema')
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Append-only enforcement for audit_log. This trigger blocks UPDATE and DELETE
-- so that audit history is immutable from inside the application. A DBA can
-- still drop the trigger if records need to be purged.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION audit_log_block_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only (operation %% rejected)', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS audit_log_no_update ON audit_log;
CREATE TRIGGER audit_log_no_update
BEFORE UPDATE ON audit_log
FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation();

DROP TRIGGER IF EXISTS audit_log_no_delete ON audit_log;
CREATE TRIGGER audit_log_no_delete
BEFORE DELETE ON audit_log
FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation();

COMMIT;
